"""The drag-to-install disk image: layout, construction and verification, standard library only.

The window a user sees when they open the image is described by a `.DS_Store` at the
volume root. Finder is never asked to lay the window out (that needs a desktop session
and Automation permission); the file is written directly, record for record what
dmgbuild 1.6.7 writes, including its fix for macOS 26.2, where Finder stopped drawing
backgrounds that also carry a bookmark (`pBBk`): the background is referenced by a
version 2 alias record only.

    build(app, image, volume_name, icon=...)   # compressed, read-only image beside the app
    verify(image, version)                     # mount it and prove what it installs
"""
from __future__ import annotations

from datetime import datetime, timedelta, timezone
import os
from pathlib import Path
import plistlib
import shutil
import struct
import subprocess
import tempfile
import time
import unicodedata

from lib.paths import ROOT

APPLICATION = "WallpaperMachine.app"
APPLICATIONS_LINK = "Applications"
BUNDLE_IDENTIFIER = "app.wallpapermachine"

# Finder window frame in points, as `bwsp` WindowBounds stores it: the title bar is
# inside this height. The background image is exactly this size, so the content area
# below the title bar is always covered, whatever height the title bar has.
WINDOW = (660, 440)
# Where the window opens. Finder keeps it on screen; y counts from the bottom.
WINDOW_ORIGIN = (420, 260)
ICON_SIZE = 128
LABEL_SIZE = 13
# Icon centres in points from the top-left of the window's content area.
APP_ICON_CENTER = (180, 205)
APPLICATIONS_ICON_CENTER = (480, 205)
# `background@2x.png` sits beside it; both are generated by scripts/brand.py.
BACKGROUND = ROOT / "Packaging/dmg/background.png"

# LZFSE: a fifth smaller than zlib and quick to verify and decompress when the user
# opens the image. Readable on every macOS the app supports.
FORMAT = "ULFO"
FILESYSTEM = "HFS+"


class DiskImageError(Exception):
    """A condition that stops building or verifying the image; the message is the whole report."""


def image_name(version):
    """The published asset: what `scripts/package.py` writes and the in-app updater selects."""
    return f"WallpaperMachine-{version}-arm64.dmg"


def volume_name(version):
    return f"WallpaperMachine {version}"


# --- .DS_Store --------------------------------------------------------------------
#
# A buddy-allocated file (documented by Mark Mentovai and Wim Lewis) holding one B-tree
# of (filename, code, type, value) records. Offsets count from byte 4, and a block's
# address is its offset ORed with log2 of its size. Every record this image needs fits
# in a single leaf, so the file is laid out exactly as the ds_store package lays out a
# fresh one: header block at 0, root block at 2048, DSDB superblock at 32, leaf at 8192.
# More records than one page holds is refused rather than split.

PAGE_SIZE = 4096
_HEADER_UNKNOWN = bytes.fromhex("0000100c000000870000200b00000000")
_ROOT_BLOCK = (2048, 11)
_SUPERBLOCK = (32, 5)
_LEAF = (8192, 13)


def _entry(filename, code, kind, value):
    name = filename.encode("utf-16-be")
    head = struct.pack(">I", len(name) // 2) + name + struct.pack(">4s4s", code, kind)
    if kind == b"long":
        return head + struct.pack(">I", value)
    if kind == b"type":
        return head + struct.pack(">4s", value)
    if kind == b"bool":
        return head + struct.pack(">?", value)
    if kind == b"blob":
        return head + struct.pack(">I", len(value)) + value
    raise ValueError(f"Unsupported .DS_Store value type {kind!r}")


def ds_store(records):
    """The bytes of a `.DS_Store` holding `records`, each `(filename, code, type, value)`.

    Finder looks records up by binary search, so they are ordered by case-folded
    filename, then by code.
    """
    entries = sorted(records, key=lambda record: (record[0].lower(), record[1]))
    leaf = struct.pack(">II", 0, len(entries)) + b"".join(_entry(*entry) for entry in entries)
    if len(leaf) > PAGE_SIZE:
        raise DiskImageError(f".DS_Store records need {len(leaf)} bytes; one B-tree page holds {PAGE_SIZE}")
    blocks = [_ROOT_BLOCK, _SUPERBLOCK, _LEAF]
    # A fresh allocator holds one free block of every width from 5 to 30 at offset
    # 2**width, except 11, whose block is the root; allocating takes the rest.
    free = {width: [1 << width] for width in range(5, 31) if width != _ROOT_BLOCK[1]}
    for offset, width in blocks[1:]:
        free[width].remove(offset)
    root = struct.pack(f">II{len(blocks)}I", len(blocks), 0, *(offset | width for offset, width in blocks))
    root += bytes(4 * (256 - len(blocks)))
    root += struct.pack(">IB4sI", 1, 4, b"DSDB", 1)
    for width in range(32):
        offsets = free.get(width, [])
        root += struct.pack(f">I{len(offsets)}I", len(offsets), *offsets)

    data = bytearray(4 + _LEAF[0] + (1 << _LEAF[1]))

    def place(offset, payload):
        data[4 + offset:4 + offset + len(payload)] = payload

    data[:4] = struct.pack(">I", 1)
    place(0, struct.pack(">4sIII16s", b"Bud1", _ROOT_BLOCK[0], 1 << _ROOT_BLOCK[1], _ROOT_BLOCK[0], _HEADER_UNKNOWN))
    place(_ROOT_BLOCK[0], root)
    place(_SUPERBLOCK[0], struct.pack(">IIIII", 2, 0, len(entries), 1, PAGE_SIZE))
    place(_LEAF[0], leaf)
    return bytes(data)


def icon_location(center):
    return struct.pack(">IIII", center[0], center[1], 0xFFFFFFFF, 0xFFFF0000)


# --- Alias record -----------------------------------------------------------------
#
# Finder resolves `backgroundImageAlias` by volume name and creation date, then by
# catalog node IDs, then by path. On HFS+ an inode number is the catalog node ID and
# a directory's birth time is its creation date.

_MAC_EPOCH = datetime(1904, 1, 1, tzinfo=timezone.utc)
_UNIX_EPOCH = datetime(1970, 1, 1, tzinfo=timezone.utc)
_TAG_FOLDER_NAME, _TAG_CNID_PATH, _TAG_CARBON_PATH = 0, 1, 2
_TAG_UNICODE_FILENAME, _TAG_UNICODE_VOLUME_NAME = 14, 15
_TAG_VOLUME_DATE, _TAG_CREATION_DATE = 16, 17
_TAG_POSIX_PATH, _TAG_MOUNT_POINT = 18, 19


def _mac_seconds(timestamp):
    """Seconds since 1904 at microsecond resolution, as alias records carry dates."""
    return (_UNIX_EPOCH + timedelta(seconds=timestamp) - _MAC_EPOCH).total_seconds()


def _tagged(tag, payload):
    return struct.pack(">hh", tag, len(payload)) + payload + (b"\0" if len(payload) & 1 else b"")


def _unicode(tag, text):
    utf16 = text.replace(":", "/").encode("utf-16-be")
    return struct.pack(">hhh", tag, len(utf16) + 2, len(utf16) // 2) + utf16


def alias(path, mount_point, volume):
    """A version 2 alias record for `path`, a file on the volume `volume` mounted at `mount_point`."""
    path, mount_point = Path(path), Path(mount_point)
    target = os.lstat(path)
    relative = os.path.relpath(path, mount_point)
    folders, head = [], os.path.dirname(relative)
    while head:
        folders.append(os.stat(mount_point / head).st_ino)
        head = os.path.dirname(head)
    return encode_alias(volume, _mac_seconds(os.stat(mount_point).st_birthtime),
                        unicodedata.normalize("NFC", str(mount_point)), os.stat(path.parent).st_ino,
                        target.st_ino, _mac_seconds(target.st_birthtime), relative, folders)


def encode_alias(volume, volume_date, mount_point, parent_cnid, cnid, creation_date, relative, folder_cnids=()):
    """The bytes of a version 2 alias record, field for field what mac_alias writes.

    Dates are seconds since 1904 (UTC); `relative` is the file's path inside the volume;
    `folder_cnids` are the catalog node IDs of the folders on that path, deepest first.
    """
    parts = relative.split("/")
    name = parts[-1]
    folder = os.path.basename(os.path.dirname(relative)) or os.path.basename(mount_point)
    fixed = struct.pack(
        ">h28pI2shI64pII4s4shhI2s10s",
        0,  # a file, not a folder
        volume.replace(":", "/").encode(),
        int(volume_date),
        b"H+",
        0,  # fixed disk
        parent_cnid,
        name.replace(":", "/").encode(),
        cnid,
        int(creation_date),
        b"\0\0\0\0",  # creator code
        b"\0\0\0\0",  # type code
        -1,  # levels from
        -1,  # levels to
        0,  # volume attributes
        b"\0\0",  # file system ID
        bytes(10),
    )
    tags = _tagged(_TAG_FOLDER_NAME, folder.replace(":", "/").encode())
    tags += struct.pack(">hhQhhQ", _TAG_VOLUME_DATE, 8, int(volume_date * 65536),
                        _TAG_CREATION_DATE, 8, int(creation_date * 65536))
    if folder_cnids:
        tags += _tagged(_TAG_CNID_PATH, struct.pack(f">{len(folder_cnids)}I", *folder_cnids))
    tags += _tagged(_TAG_CARBON_PATH, volume.encode() + b":" + b":\0".join(part.replace(":", "/").encode() for part in parts))
    tags += _unicode(_TAG_UNICODE_FILENAME, name)
    tags += _unicode(_TAG_UNICODE_VOLUME_NAME, volume)
    tags += _tagged(_TAG_POSIX_PATH, ("/" + relative).encode())
    tags += _tagged(_TAG_MOUNT_POINT, mount_point.encode())
    tags += struct.pack(">hh", -1, 0)
    body = fixed + tags
    return struct.pack(">4shh", b"\0\0\0\0", 8 + len(body), 2) + body


def layout_records(background_alias):
    """Every `.DS_Store` record of the image's root window."""
    window = {
        "ContainerShowSidebar": False,
        "PreviewPaneVisibility": False,
        "ShowPathbar": False,
        "ShowSidebar": False,
        "ShowStatusBar": False,
        "ShowTabView": False,
        "ShowToolbar": False,
        "SidebarWidth": 180,
        "WindowBounds": "{{%d, %d}, {%d, %d}}" % (*WINDOW_ORIGIN, *WINDOW),
    }
    icons = {
        "arrangeBy": "none",
        "backgroundColorBlue": 1.0,
        "backgroundColorGreen": 1.0,
        "backgroundColorRed": 1.0,
        "backgroundImageAlias": background_alias,
        "backgroundType": 2,  # picture
        "gridOffsetX": 0.0,
        "gridOffsetY": 0.0,
        "gridSpacing": 100.0,
        "iconSize": float(ICON_SIZE),
        "labelOnBottom": True,
        "scrollPositionX": 0.0,
        "scrollPositionY": 0.0,
        "showIconPreview": False,
        "showItemInfo": False,
        "textSize": float(LABEL_SIZE),
        "viewOptionsVersion": 1,
    }
    return [
        (".", b"bwsp", b"blob", plistlib.dumps(window, fmt=plistlib.FMT_BINARY)),
        (".", b"icvl", b"type", b"icnv"),
        (".", b"icvp", b"blob", plistlib.dumps(icons, fmt=plistlib.FMT_BINARY)),
        (".", b"vSrn", b"long", 1),
        (APPLICATIONS_LINK, b"Iloc", b"blob", icon_location(APPLICATIONS_ICON_CENTER)),
        (APPLICATION, b"Iloc", b"blob", icon_location(APP_ICON_CENTER)),
    ]


# --- hdiutil ----------------------------------------------------------------------


def _run(command, error):
    """Run a tool quietly; its output is reported only when it fails."""
    completed = subprocess.run(list(map(str, command)), capture_output=True)
    if completed.returncode != 0:
        detail = (completed.stderr or completed.stdout).decode(errors="replace").strip()
        raise DiskImageError(f"{error}: {detail}")
    return completed.stdout


def _attach(image, *options):
    """Attach an image without showing it in Finder; its device and mount point."""
    listing = plistlib.loads(_run(["/usr/bin/hdiutil", "attach", "-nobrowse", "-noautoopen", *options, "-plist", image],
                                  f"Could not attach {image}"))
    for entity in listing.get("system-entities", []):
        if entity.get("mount-point"):
            return entity["dev-entry"], Path(entity["mount-point"])
    raise DiskImageError(f"{image} attached without a mountable volume")


def _detach(target):
    """Detach, waiting out the brief busy spell that follows writes, then forcing."""
    for delay in (0, 1, 2, 4):
        time.sleep(delay)
        if subprocess.run(["/usr/bin/hdiutil", "detach", str(target)], capture_output=True).returncode == 0:
            return
    _run(["/usr/bin/hdiutil", "detach", "-force", target], f"Could not detach {target}")


def _tree_size(path):
    total = 0
    for directory, _, files in os.walk(path):
        for name in files:
            total += -(-os.lstat(os.path.join(directory, name)).st_size // 4096) * 4096
    return total


def _flag_custom_icon(folder):
    """Set kHasCustomIcon in the folder's Finder info so Finder shows `.VolumeIcon.icns`."""
    finder_info = bytes(8) + struct.pack(">H", 0x0400) + bytes(22)
    _run(["/usr/bin/xattr", "-wx", "com.apple.FinderInfo", finder_info.hex(), folder],
         f"Could not flag the custom volume icon on {folder}")


def _populate(mount, name, app, background, icon):
    shutil.copyfile(background, mount / ".background.tiff")
    if icon is not None:
        shutil.copyfile(icon, mount / ".VolumeIcon.icns")
        _flag_custom_icon(mount)
    # ditto keeps the bundle's code signatures and symlinks. Extended attributes and
    # resource forks stay behind: a synced checkout's File Provider keeps adding
    # com.apple.FinderInfo and fpfs attributes to the bundle in build/, which
    # `codesign --strict` rejects, and a signature never lives in either.
    _run(["/usr/bin/ditto", "--norsrc", "--noextattr", app, mount / APPLICATION], f"Could not copy {app} into the image")
    os.symlink("/Applications", mount / APPLICATIONS_LINK)
    records = layout_records(alias(mount / ".background.tiff", mount, name))
    (mount / ".DS_Store").write_bytes(ds_store(records))
    shutil.rmtree(mount / ".Trashes", ignore_errors=True)


def retina(background):
    background = Path(background)
    return background.with_name(f"{background.stem}@2x{background.suffix}")


def _png_size(path):
    with open(path, "rb") as handle:
        header = handle.read(24)
    if header[:8] != b"\x89PNG\r\n\x1a\n" or header[12:16] != b"IHDR":
        raise DiskImageError(f"{path} is not a PNG")
    return struct.unpack(">II", header[16:24])


def check_inputs(icon=None, background=BACKGROUND):
    """Refuse a missing volume icon or window art, or a 1x/2x pair that does not match.

    scripts/package.py runs this in its preflight, while the bundle is still
    untouched, so fixing the art never needs a fresh build.
    """
    background = Path(background)
    missing = [str(path) for path in (background, retina(background), icon) if path is not None and not Path(path).is_file()]
    if missing:
        raise DiskImageError("Missing disk image input (python3 scripts/brand.py --dmg draws the art): " + ", ".join(missing))
    small, large = _png_size(background), _png_size(retina(background))
    if large != (small[0] * 2, small[1] * 2):
        raise DiskImageError(f"{retina(background).name} is {large[0]}×{large[1]} pixels, not twice {background.name}'s "
                             f"{small[0]}×{small[1]}; regenerate both with python3 scripts/brand.py --dmg")


def build(app, image, name, icon=None, background=BACKGROUND):
    """Write `image`, a compressed read-only disk image of `app` laid out for drag-to-install.

    `name` is the volume name, which is also the window title; `icon` an `.icns` for
    the volume. The background is `background` and its `@2x` twin, joined into one
    HiDPI TIFF.
    """
    app, image, background = Path(app), Path(image), Path(background)
    if not app.is_dir():
        raise DiskImageError(f"Missing disk image input: {app}")
    check_inputs(icon, background)
    image.parent.mkdir(parents=True, exist_ok=True)
    with tempfile.TemporaryDirectory(prefix=".dmg-", dir=image.parent) as scratch:
        work = Path(scratch)
        tiff = work / "background.tiff"
        _run(["/usr/bin/tiffutil", "-cathidpicheck", background, retina(background), "-out", tiff],
             f"tiffutil could not join {background.name} and its @2x twin")
        writable = work / "writable.dmg"
        size = 64 * 1024 * 1024 + _tree_size(app) + tiff.stat().st_size + (Path(icon).stat().st_size if icon else 0)
        _run(["/usr/bin/hdiutil", "create", "-ov", "-volname", name, "-fs", FILESYSTEM,
              "-fsargs", "-c c=64,a=16,e=16", "-size", f"{-(-size // 1024)}k", writable],
             "Could not create the writable image")
        device, mount = _attach(writable, "-owners", "off")
        try:
            _populate(mount, name, app, tiff, icon)
        except BaseException:
            subprocess.run(["/usr/bin/hdiutil", "detach", "-force", device], capture_output=True)
            raise
        _detach(device)
        _run(["/usr/bin/hdiutil", "resize", "-sectors", "min", writable], "Could not shrink the image")
        image.unlink(missing_ok=True)
        _run(["/usr/bin/hdiutil", "convert", writable, "-format", FORMAT, "-o", image],
             "Could not compress the image")
    return image


def verify(image, version):
    """Mount `image` read-only and prove it installs `version` of this app.

    The checks are the ones a user relies on: the bundle is this app at that version,
    its signature survived the round trip, the Applications link is there to drag
    onto, and the window layout and its background travelled with it.
    """
    image = Path(image)
    with tempfile.TemporaryDirectory(prefix="dmg-verify-") as scratch:
        mount = Path(scratch) / "volume"
        mount.mkdir()
        _attach(image, "-readonly", "-mountpoint", mount)
        try:
            app = mount / APPLICATION
            info = app / "Contents/Info.plist"
            if not info.is_file():
                raise DiskImageError(f"{image.name} holds no {APPLICATION}")
            with info.open("rb") as handle:
                values = plistlib.load(handle)
            if values.get("CFBundleIdentifier") != BUNDLE_IDENTIFIER:
                raise DiskImageError(f"{image.name} holds {values.get('CFBundleIdentifier')!r}, not {BUNDLE_IDENTIFIER}")
            if values.get("CFBundleShortVersionString") != version:
                raise DiskImageError(f"{image.name} holds version {values.get('CFBundleShortVersionString')}, not {version}")
            _run(["/usr/bin/codesign", "--verify", "--deep", "--strict", app], f"{APPLICATION} in {image.name} fails codesign")
            link = mount / APPLICATIONS_LINK
            if not link.is_symlink() or os.readlink(link) != "/Applications":
                raise DiskImageError(f"{image.name} has no {APPLICATIONS_LINK} link to /Applications")
            absent = [name for name in (".DS_Store", ".background.tiff") if not (mount / name).is_file()]
            if absent:
                raise DiskImageError(f"{image.name} lacks its window layout: {', '.join(absent)}")
        finally:
            _detach(mount)
