use std::collections::BTreeMap;

use smol_str::SmolStr;

use crate::{
    ShaderError, ShaderResult, ShaderStageKind,
    legalize::{LegacyTypeName, SamplerType, StageResourceLayout, UniformMember},
    pipeline::inputs::ProgramStageInputs,
    preprocess::{MacroTable, PreprocessedStage},
    syntax::{DeclarationArraySize, DeclarationArraySuffix, SyntaxItem, TopLevelQualifier},
};

/// Program-level descriptor layout for resources generated by codegen.
#[derive(Clone, Debug, Eq, PartialEq)]
pub(super) struct ProgramResourceLayout {
    /// Shared binding for generated `GlobalUniforms`, when any stage needs it.
    uniform_block_binding: Option<u32>,
    /// Program-wide set zero descriptor bindings reserved by kept source
    /// resources.
    reserved_bindings: Vec<u32>,
    /// Program-wide descriptor bindings assigned to generated split textures.
    texture_bindings: ProgramTextureResourceBindings,
    /// Program-wide members for generated `GlobalUniforms`.
    uniform_members: Vec<UniformMember>,
}

impl ProgramResourceLayout {
    /// Builds program-wide resource bindings from all parsed stage
    /// declarations.
    pub(super) fn build_from_stage_inputs(
        stage_inputs: &ProgramStageInputs<'_>,
    ) -> ShaderResult<Self> {
        let stages = stage_inputs.stages();
        let mut reservations = ProgramBindingReservations::default();
        let mut explicit_uniform_binding = None;
        let mut uniform_members = Vec::<UniformMember>::new();
        let mut textures = Vec::new();

        for kind in [ShaderStageKind::Vertex, ShaderStageKind::Fragment] {
            for stage in stages.iter().filter(|stage| stage.stage.kind() == kind) {
                for item in stage.module.items() {
                    let SyntaxItem::Declaration(declaration) = item else {
                        continue;
                    };
                    match ProgramResourceDeclarationKind::new(stage.stage, declaration) {
                        ProgramResourceDeclarationKind::Texture(texture) => {
                            if let Some(binding) = texture.encoded_binding() {
                                binding.reserve_for(texture, &mut reservations)?;
                            }
                            textures.push(ProgramTextureResource {
                                stage: kind,
                                declaration: texture,
                            });
                        }
                        ProgramResourceDeclarationKind::UniformMember(uniform) => {
                            let explicit_binding = uniform.explicit_binding();
                            let member = uniform.into_supported_member()?;
                            if let Some(previous) = uniform_members
                                .iter()
                                .position(|previous| previous.name == member.name)
                            {
                                if !member.has_same_layout(&uniform_members[previous]) {
                                    return Err(ShaderError::invalid_request(
                                        "conflicting GlobalUniforms member declarations",
                                    ));
                                }
                            } else {
                                uniform_members.push(member.into_uniform_member());
                            }
                            if let Some(binding) = explicit_binding {
                                if let Some(previous) = explicit_uniform_binding
                                    && previous != binding
                                {
                                    return Err(ShaderError::invalid_request(
                                        "conflicting explicit GlobalUniforms descriptor bindings",
                                    ));
                                }
                                explicit_uniform_binding = Some(binding);
                            }
                        }
                        ProgramResourceDeclarationKind::KeptResource(resource) => {
                            if let Some(binding) = resource.layout_binding {
                                binding.reserve_for(resource, &mut reservations)?;
                            }
                        }
                        ProgramResourceDeclarationKind::Other => {}
                    }
                }
            }
        }

        let reserved_bindings = reservations.set_zero_binding_indices().collect();
        let uniform_block_binding = if uniform_members.is_empty() {
            None
        } else {
            let binding = explicit_uniform_binding.unwrap_or_else(|| {
                let mut binding = 0u32;
                while reservations.contains_binding(binding) {
                    binding += 1;
                }
                binding
            });
            reservations.reserve(
                binding,
                ProgramBindingReservation {
                    name: SmolStr::new("GlobalUniforms"),
                    kind: ProgramBindingReservationKind::GeneratedUniformBlock,
                },
            )?;
            Some(binding)
        };

        let mut allocator = ProgramResourceAllocator { reservations };
        let texture_bindings = ProgramTextureResourceBindings {
            assignments: allocator.assign_textures(textures)?,
        };

        Ok(Self {
            uniform_block_binding,
            reserved_bindings,
            texture_bindings,
            uniform_members,
        })
    }
}

impl Default for ProgramResourceLayout {
    fn default() -> Self {
        static EMPTY_STAGES: [PreprocessedStage; 0] = [];

        let inputs =
            ProgramStageInputs::parse(EMPTY_STAGES.as_slice()).expect("empty stage inputs parse");
        Self::build_from_stage_inputs(&inputs).expect("empty resource layout builds")
    }
}

impl ProgramResourceLayout {
    /// Builds the legalizer-facing resource layout for one stage.
    pub(super) fn stage_layout(&self) -> StageResourceLayout {
        let mut layout = StageResourceLayout::default();
        layout.uniform_block_binding = self.uniform_block_binding;
        layout.reserved_bindings.clone_from(&self.reserved_bindings);
        layout.uniform_members.clone_from(&self.uniform_members);
        for assignment in &self.texture_bindings.assignments {
            layout.push_texture_binding(
                assignment.stage,
                assignment.name.clone(),
                assignment.texture_binding,
                assignment.sampler_binding,
            );
        }
        layout
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn resource_layout_constructor_accepts_empty_stage_inputs() {
        let stages = Vec::<PreprocessedStage>::new();
        let inputs = ProgramStageInputs::parse(stages.as_slice()).expect("empty inputs parse");
        let layout =
            ProgramResourceLayout::build_from_stage_inputs(&inputs).expect("empty layout builds");

        assert_eq!(layout, ProgramResourceLayout::default());
    }
}

/// Program-wide split texture descriptor assignments.
#[derive(Clone, Debug, Default, Eq, PartialEq)]
struct ProgramTextureResourceBindings {
    /// Assignments in deterministic stage/source order.
    assignments: Vec<ProgramTextureResourceBinding>,
}

/// Program-level split texture resource tagged with its owning stage.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
struct ProgramTextureResource<'src> {
    /// Stage containing the source texture declaration.
    stage: ShaderStageKind,
    /// Source texture declaration.
    declaration: TextureResourceDeclaration<'src>,
}

/// Program-level descriptor binding assignment for one split texture.
#[derive(Clone, Debug, Eq, PartialEq)]
struct ProgramTextureResourceBinding {
    /// Stage containing the source declaration.
    stage: ShaderStageKind,
    /// Source texture variable name.
    name: SmolStr,
    /// Descriptor binding assigned to the generated texture handle.
    texture_binding: u32,
    /// Descriptor binding assigned to the generated sampler.
    sampler_binding: u32,
}

/// Program-wide descriptor binding allocator for generated resources.
#[derive(Clone, Debug, Default, Eq, PartialEq)]
struct ProgramResourceAllocator {
    /// Descriptor bindings already occupied in the program.
    reservations: ProgramBindingReservations,
}

impl ProgramResourceAllocator {
    /// Assigns texture and generated sampler descriptor bindings for all
    /// split texture declarations, reusing one logical resource assignment
    /// when the same source texture appears in multiple stages.
    fn assign_textures(
        &mut self,
        textures: Vec<ProgramTextureResource<'_>>,
    ) -> ShaderResult<Vec<ProgramTextureResourceBinding>> {
        let mut by_name = Vec::<(SmolStr, ProgramTextureResourceBinding)>::new();
        let mut assignments = Vec::with_capacity(textures.len());
        for texture in textures {
            if let Some((_, previous)) = by_name
                .iter()
                .find(|(name, _)| *name == texture.declaration.name)
            {
                assignments.push(ProgramTextureResourceBinding {
                    stage: texture.stage,
                    name: SmolStr::new(texture.declaration.name),
                    texture_binding: previous.texture_binding,
                    sampler_binding: previous.sampler_binding,
                });
                continue;
            }

            let assignment = self.assign_texture(texture)?;
            by_name.push((assignment.name.clone(), assignment.clone()));
            assignments.push(assignment);
        }
        Ok(assignments)
    }

    /// Assigns texture and generated sampler descriptor bindings for one
    /// split texture declaration.
    fn assign_texture(
        &mut self,
        texture: ProgramTextureResource<'_>,
    ) -> ShaderResult<ProgramTextureResourceBinding> {
        let texture_binding = if let Some(binding) = texture.declaration.encoded_binding() {
            binding.reserve_for(texture.declaration, &mut self.reservations)?;
            binding.descriptor.binding
        } else {
            self.allocate(ProgramBindingReservation {
                name: SmolStr::new(texture.declaration.name),
                kind: ProgramBindingReservationKind::GeneratedTexture,
            })
        };
        let sampler_binding = self.allocate(ProgramBindingReservation {
            name: SmolStr::new(texture.declaration.name),
            kind: ProgramBindingReservationKind::GeneratedSampler,
        });

        Ok(ProgramTextureResourceBinding {
            stage: texture.stage,
            name: SmolStr::new(texture.declaration.name),
            texture_binding,
            sampler_binding,
        })
    }

    /// Allocates the lowest unoccupied binding.
    fn allocate(&mut self, reservation: ProgramBindingReservation) -> u32 {
        let mut binding = 0u32;
        while self.reservations.contains_binding(binding) {
            binding += 1;
        }
        self.reservations
            .reserve(binding, reservation)
            .expect("fresh descriptor binding should be reservable");
        binding
    }
}

/// Program-wide descriptor binding reservations keyed by set and binding
/// number.
#[derive(Clone, Debug, Default, Eq, PartialEq)]
struct ProgramBindingReservations {
    /// Reservation identity for each occupied binding.
    ///
    /// Kept ordered because set/binding key iteration feeds deterministic
    /// generated descriptor layout.
    bindings: BTreeMap<ProgramDescriptorBinding, ProgramBindingReservation>,
}

impl ProgramBindingReservations {
    /// Reserves one descriptor binding for a typed logical resource.
    fn reserve(
        &mut self,
        binding: u32,
        reservation: ProgramBindingReservation,
    ) -> ShaderResult<()> {
        self.reserve_descriptor(ProgramDescriptorBinding::set_zero(binding), reservation)
    }

    /// Reserves one descriptor set/binding pair for a typed logical resource.
    fn reserve_descriptor(
        &mut self,
        descriptor: ProgramDescriptorBinding,
        reservation: ProgramBindingReservation,
    ) -> ShaderResult<()> {
        if let Some(previous) = self.bindings.get(&descriptor) {
            if *previous == reservation {
                return Ok(());
            }
            return Err(ShaderError::invalid_request(
                "descriptor binding is already reserved by an incompatible resource",
            ));
        }
        let _previous = self.bindings.insert(descriptor, reservation);
        Ok(())
    }

    /// Returns whether any resource already occupies `binding`.
    fn contains_binding(&self, binding: u32) -> bool {
        self.bindings
            .contains_key(&ProgramDescriptorBinding::set_zero(binding))
    }

    /// Iterates occupied set zero binding numbers.
    fn set_zero_binding_indices(&self) -> impl Iterator<Item = u32> + '_ {
        self.bindings
            .keys()
            .filter(|descriptor| descriptor.set == 0)
            .map(|descriptor| descriptor.binding)
    }
}

/// Descriptor set/binding pair used by program-wide reservations.
#[derive(Clone, Copy, Debug, Eq, Ord, PartialEq, PartialOrd)]
struct ProgramDescriptorBinding {
    /// Descriptor set index.
    set: u32,
    /// Descriptor binding index within the set.
    binding: u32,
}

impl ProgramDescriptorBinding {
    /// Creates a set zero descriptor binding.
    const fn set_zero(binding: u32) -> Self {
        Self { set: 0, binding }
    }
}

/// Typed logical identity for a program descriptor binding reservation.
#[derive(Clone, Debug, Eq, PartialEq)]
struct ProgramBindingReservation {
    /// Source or generated resource name.
    name: SmolStr,
    /// Descriptor/resource kind occupying the binding.
    kind: ProgramBindingReservationKind,
}

/// Descriptor/resource kind included in binding reservation identity.
#[derive(Clone, Debug, Eq, PartialEq)]
enum ProgramBindingReservationKind {
    /// Texture descriptor generated from a source `sampler2D`.
    SplitTexture {
        /// Generated backend texture type.
        ty: &'static str,
    },
    /// Kept source descriptor resource.
    KeptResource {
        /// Source resource type.
        ty: SmolStr,
    },
    /// Generated `GlobalUniforms` descriptor.
    GeneratedUniformBlock,
    /// Generated texture descriptor without an encoded binding.
    GeneratedTexture,
    /// Generated sampler paired with a split texture.
    GeneratedSampler,
}

/// Supported program-wide uniform block member declaration.
#[derive(Clone, Debug, Eq, PartialEq)]
struct ProgramUniformMember {
    /// Source type name.
    ty: SmolStr,
    /// Source variable name.
    name: SmolStr,
    /// Optional array suffix following the declaration name.
    array_suffix: Option<SmolStr>,
    /// Explicit layout binding parsed from source, when present.
    explicit_binding: Option<u32>,
}

impl ProgramUniformMember {
    /// Returns whether another declaration would occupy the same block layout.
    fn has_same_layout(&self, other: &UniformMember) -> bool {
        LegacyTypeName::new(other.ty.as_str())
            .validate_generated_uniform()
            .is_ok_and(|other_ty| self.ty.as_str() == other_ty.as_str())
            && self.name == other.name
            && self.array_suffix.as_deref() == other.array_suffix.as_deref()
    }

    /// Converts this supported declaration into the legalizer resource model.
    fn into_uniform_member(self) -> UniformMember {
        UniformMember {
            ty: self.ty,
            name: self.name,
            array_suffix: self.array_suffix,
            explicit_binding: self.explicit_binding,
            binding: None,
        }
    }
}

/// Program-level resource declaration kind.
#[derive(Clone, Debug, Eq, PartialEq)]
enum ProgramResourceDeclarationKind<'src> {
    /// Texture resource with an optional encoded binding.
    Texture(TextureResourceDeclaration<'src>),
    /// Scalar/vector uniform that contributes to `GlobalUniforms`.
    UniformMember(UniformResourceDeclaration<'src>),
    /// Kept descriptor resource with an optional explicit binding.
    KeptResource(KeptResourceDeclaration<'src>),
    /// Any declaration that does not participate in descriptor layout.
    Other,
}

impl<'src> ProgramResourceDeclarationKind<'src> {
    /// Constructs compact resource facts from a source declaration.
    #[allow(clippy::single_call_fn)]
    fn new(
        stage: &'src PreprocessedStage,
        declaration: &'src crate::syntax::ShaderDeclaration<'src>,
    ) -> Self {
        if declaration.qualifier() != Some(TopLevelQualifier::Uniform) {
            return Self::Other;
        }
        let (Some(ty), Some(name)) = (declaration.type_name(), declaration.name()) else {
            return Self::Other;
        };

        let layout_binding = declaration.layout().and_then(|layout| {
            Some(LayoutBindingFact {
                set: layout.set(),
                binding: layout.binding()?,
            })
        });
        if let Some(sampler) = SamplerType::new(ty) {
            if sampler.supports_texture_split() {
                Self::Texture(TextureResourceDeclaration {
                    name,
                    binding: TextureBindingFact::new(name),
                })
            } else {
                Self::KeptResource(KeptResourceDeclaration {
                    ty,
                    name,
                    layout_binding,
                })
            }
        } else {
            Self::UniformMember(UniformResourceDeclaration {
                stage: stage.kind(),
                macros: stage.macros(),
                ty,
                name,
                array_suffix: declaration.array_suffix(),
                layout_binding,
            })
        }
    }
}

/// Program-level texture declaration.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
struct TextureResourceDeclaration<'src> {
    /// Source texture name.
    name: &'src str,
    /// Binding fact encoded in the source name.
    binding: Option<TextureBindingFact<'src>>,
}

impl<'src> TextureResourceDeclaration<'src> {
    /// Returns this texture's typed binding reservation identity.
    fn reservation(self) -> ProgramBindingReservation {
        ProgramBindingReservation {
            name: SmolStr::new(self.name),
            kind: ProgramBindingReservationKind::SplitTexture { ty: "texture2D" },
        }
    }

    /// Returns the encoded descriptor binding fact.
    const fn encoded_binding(self) -> Option<TextureBindingFact<'src>> {
        self.binding
    }
}

/// Program-level resource declaration kept in source.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
struct KeptResourceDeclaration<'src> {
    /// Source resource type.
    ty: &'src str,
    /// Source resource name.
    name: &'src str,
    /// Explicit descriptor binding parsed from the syntax layout fact.
    layout_binding: Option<LayoutBindingFact>,
}

impl KeptResourceDeclaration<'_> {
    /// Returns this resource's typed binding reservation identity.
    fn reservation(self) -> ProgramBindingReservation {
        ProgramBindingReservation {
            name: SmolStr::new(self.name),
            kind: ProgramBindingReservationKind::KeptResource {
                ty: SmolStr::new(self.ty),
            },
        }
    }
}

/// Typed texture binding fact parsed from a source texture name.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
struct TextureBindingFact<'src> {
    /// Source texture name carrying the fact.
    name: &'src str,
    /// Descriptor binding represented by the name.
    descriptor: ProgramDescriptorBinding,
}

impl<'src> TextureBindingFact<'src> {
    /// Constructs a typed fixed binding fact from a `g_TextureN` name.
    #[allow(clippy::single_call_fn)]
    fn new(name: &'src str) -> Option<Self> {
        let suffix = name.strip_prefix("g_Texture")?;
        if suffix.is_empty()
            || !suffix.chars().all(|character| character.is_ascii_digit())
            || suffix.len() > 1 && suffix.starts_with('0')
        {
            return None;
        }

        suffix.parse::<u32>().ok().map(|binding| Self {
            name,
            descriptor: ProgramDescriptorBinding::set_zero(binding),
        })
    }

    /// Reserves this binding for a split texture declaration.
    fn reserve_for(
        self,
        texture: TextureResourceDeclaration<'src>,
        reservations: &mut ProgramBindingReservations,
    ) -> ShaderResult<()> {
        debug_assert_eq!(self.name, texture.name);
        reservations.reserve_descriptor(self.descriptor, texture.reservation())
    }
}

/// Program-level uniform declaration.
#[derive(Clone, Debug, Eq, PartialEq)]
struct UniformResourceDeclaration<'src> {
    /// Stage containing the source declaration.
    stage: ShaderStageKind,
    /// Typed macro facts visible to this declaration.
    macros: &'src MacroTable,
    /// Source type name.
    ty: &'src str,
    /// Source variable name.
    name: &'src str,
    /// Optional array suffix following the declaration name.
    array_suffix: Option<DeclarationArraySuffix<'src>>,
    /// Explicit layout binding parsed by syntax, when present.
    layout_binding: Option<LayoutBindingFact>,
}

impl UniformResourceDeclaration<'_> {
    /// Returns the explicit descriptor binding, when source declared one.
    fn explicit_binding(&self) -> Option<u32> {
        self.layout_binding.map(|binding| binding.binding)
    }

    /// Converts this source declaration into a replay-safe program member.
    fn into_supported_member(self) -> ShaderResult<ProgramUniformMember> {
        let ty = LegacyTypeName::new(self.ty)
            .validate_generated_uniform()?
            .as_str();
        let explicit_binding = self.explicit_binding();
        let array_suffix = self
            .array_suffix
            .as_ref()
            .map(|suffix| match suffix.size() {
                Some(DeclarationArraySize::Numeric(count)) => {
                    Ok(SmolStr::new(format!("[{count}]")))
                }
                Some(DeclarationArraySize::MacroIdentifier(identifier)) => {
                    let Some(count) = self
                        .macros
                        .value(identifier.as_str())
                        .and_then(|value| value.parse::<u32>().ok())
                    else {
                        return Err(ShaderError::invalid_request(format!(
                            "unresolved GlobalUniforms member array suffix `{}` in {:?} stage",
                            suffix.as_str(),
                            self.stage
                        )));
                    };
                    Ok(SmolStr::new(format!("[{count}]")))
                }
                None => Err(ShaderError::invalid_request(format!(
                    "unresolved GlobalUniforms member array suffix `{}` in {:?} stage",
                    suffix.as_str(),
                    self.stage
                ))),
            })
            .transpose()?;
        Ok(ProgramUniformMember {
            ty: SmolStr::new(ty),
            name: SmolStr::new(self.name),
            array_suffix,
            explicit_binding,
        })
    }
}

/// Typed layout binding fact parsed from syntax layout text.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
struct LayoutBindingFact {
    /// Descriptor set index.
    set: Option<u32>,
    /// Descriptor binding index.
    binding: u32,
}

impl LayoutBindingFact {
    /// Returns the descriptor set/binding pair for this layout fact.
    const fn descriptor(self) -> ProgramDescriptorBinding {
        ProgramDescriptorBinding {
            set: match self.set {
                Some(set) => set,
                None => 0,
            },
            binding: self.binding,
        }
    }

    /// Reserves this binding for a kept source resource.
    fn reserve_for(
        self,
        resource: KeptResourceDeclaration<'_>,
        reservations: &mut ProgramBindingReservations,
    ) -> ShaderResult<()> {
        reservations.reserve_descriptor(self.descriptor(), resource.reservation())
    }
}
